name: pia-watch           # ← ワークフロー名は自由に変えてOK

on:
  schedule:
    - cron: "*/2 * * * *"   # 2分おき
  workflow_dispatch:        # 手動実行ボタン

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright browsers        # ★ 追加したステップ
        run: playwright install --with-deps      # ★ ここまで 2 行

      - name: Run monitors
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          python monitor.py
          python relief_monitor.py
