name: relief-watch

on:
  schedule:
    - cron: '0 * * * *'          # 毎時 00 分にジョブ起動（UTC）
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 80          # ←★① ここを 80 に伸ばす

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Watch RELIEF page every 2 min for 1 h
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          for i in $(seq 1 30); do
            echo "---- $(date '+%F %T')  (#$i/30) ----"
            python relief_monitor.py
            sleep 110               # ←★② ここを 110 秒に短縮
          done

            echo "---- $(date '+%F %T')  (#$i/30) ----"
            python relief_monitor.py
            sleep 120   # 2分待つ
          done
